"""initial schema

Revision ID: 5faa0b6b68f1
Revises: 
Create Date: 2026-07-27 17:17:31.076885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5faa0b6b68f1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_flags',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('performance_learning_feedback',
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('insight', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('based_on_video_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('youtube_channel_id', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt_templates',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('artifact_type', sa.Enum('SCRIPT', 'IMAGE', 'VIDEO', 'VOICE', 'MUSIC', 'THUMBNAIL', 'METADATA', 'PROMPT', 'LOG', name='prompt_template_artifact_type'), nullable=False),
    sa.Column('template_text', sa.Text(), nullable=False),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('model_used', sa.String(length=255), nullable=True),
    sa.Column('revision_notes', sa.Text(), nullable=True),
    sa.Column('is_deprecated', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('providers',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.Enum('LLM', 'IMAGE_GEN', 'VIDEO_GEN', 'VOICE_GEN', 'MUSIC_GEN', 'COMPUTE', name='provider_category'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_fallback', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('workflow_runs',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('topic', sa.String(length=500), nullable=True),
    sa.Column('mode', sa.Enum('MANUAL', 'ASSISTED', 'AUTONOMOUS', name='workflow_mode'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'AWAITING_APPROVAL', 'COMPLETED', 'FAILED', name='workflow_status'), nullable=False),
    sa.Column('current_stage', sa.String(length=100), nullable=True),
    sa.Column('total_cost_usd', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approval_checkpoints',
    sa.Column('workflow_run_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.Enum('TREND_SELECTION', 'SCRIPT', 'STORYBOARD', 'PROMPT', 'IMAGE', 'VIDEO', 'THUMBNAIL', name='approval_stage'), nullable=False),
    sa.Column('reference_table', sa.String(length=100), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('APPROVE', 'REJECT', 'RETRY', 'MANUAL_EDIT', 'CONTINUE', name='approval_action'), nullable=True),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artifacts',
    sa.Column('workflow_run_id', sa.UUID(), nullable=False),
    sa.Column('artifact_type', sa.Enum('SCRIPT', 'IMAGE', 'VIDEO', 'VOICE', 'MUSIC', 'THUMBNAIL', 'METADATA', 'PROMPT', 'LOG', name='artifact_type'), nullable=False),
    sa.Column('reference_table', sa.String(length=100), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets',
    sa.Column('workflow_run_id', sa.UUID(), nullable=False),
    sa.Column('asset_type', sa.String(length=50), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('provider_name', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generation_attempts',
    sa.Column('workflow_run_id', sa.UUID(), nullable=False),
    sa.Column('reference_table', sa.String(length=100), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('validation_failure', sa.Text(), nullable=True),
    sa.Column('provider_id', sa.UUID(), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generation_learning_events',
    sa.Column('workflow_run_id', sa.UUID(), nullable=False),
    sa.Column('validator_name', sa.String(length=100), nullable=False),
    sa.Column('reference_table', sa.String(length=100), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=False),
    sa.Column('issue_detected', sa.Text(), nullable=False),
    sa.Column('correction_applied', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompts',
    sa.Column('workflow_run_id', sa.UUID(), nullable=False),
    sa.Column('artifact_type', sa.Enum('SCRIPT', 'IMAGE', 'VIDEO', 'VOICE', 'MUSIC', 'THUMBNAIL', 'METADATA', 'PROMPT', 'LOG', name='prompt_artifact_type'), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('negative_prompt', sa.Text(), nullable=True),
    sa.Column('model_used', sa.String(length=255), nullable=True),
    sa.Column('prompt_template_id', sa.UUID(), nullable=True),
    sa.Column('template_version', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_version_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'GENERATED', 'APPROVED', 'REJECTED', name='asset_status'), nullable=False),
    sa.Column('retry_reason', sa.String(), nullable=True),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prompt_template_id'], ['prompt_templates.id'], ),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provider_usage_logs',
    sa.Column('workflow_run_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.String(length=100), nullable=True),
    sa.Column('units_consumed', sa.Float(), nullable=True),
    sa.Column('unit_label', sa.String(length=50), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quality_score_details',
    sa.Column('workflow_run_id', sa.UUID(), nullable=False),
    sa.Column('reference_table', sa.String(length=100), nullable=False),
    sa.Column('reference_id', sa.UUID(), nullable=False),
    sa.Column('dimension', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('scored_by', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scripts',
    sa.Column('workflow_run_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('validation_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_version_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'GENERATED', 'APPROVED', 'REJECTED', name='asset_status'), nullable=False),
    sa.Column('retry_reason', sa.String(), nullable=True),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_logs',
    sa.Column('workflow_run_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('storyboards',
    sa.Column('script_id', sa.UUID(), nullable=False),
    sa.Column('shots', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('validation_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_version_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'GENERATED', 'APPROVED', 'REJECTED', name='asset_status'), nullable=False),
    sa.Column('retry_reason', sa.String(), nullable=True),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['script_id'], ['scripts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('thumbnails',
    sa.Column('workflow_run_id', sa.UUID(), nullable=False),
    sa.Column('prompt_id', sa.UUID(), nullable=True),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('provider_name', sa.String(length=100), nullable=True),
    sa.Column('validation_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_version_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'GENERATED', 'APPROVED', 'REJECTED', name='asset_status'), nullable=False),
    sa.Column('retry_reason', sa.String(), nullable=True),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generated_videos',
    sa.Column('storyboard_id', sa.UUID(), nullable=False),
    sa.Column('prompt_id', sa.UUID(), nullable=True),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('shot_number', sa.Integer(), nullable=True),
    sa.Column('provider_name', sa.String(length=100), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('validation_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_version_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'GENERATED', 'APPROVED', 'REJECTED', name='asset_status'), nullable=False),
    sa.Column('retry_reason', sa.String(), nullable=True),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ),
    sa.ForeignKeyConstraint(['storyboard_id'], ['storyboards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('images',
    sa.Column('storyboard_id', sa.UUID(), nullable=False),
    sa.Column('prompt_id', sa.UUID(), nullable=True),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('shot_number', sa.Integer(), nullable=True),
    sa.Column('provider_name', sa.String(length=100), nullable=True),
    sa.Column('validation_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_version_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'GENERATED', 'APPROVED', 'REJECTED', name='asset_status'), nullable=False),
    sa.Column('retry_reason', sa.String(), nullable=True),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ),
    sa.ForeignKeyConstraint(['storyboard_id'], ['storyboards.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('videos',
    sa.Column('workflow_run_id', sa.UUID(), nullable=False),
    sa.Column('thumbnail_id', sa.UUID(), nullable=True),
    sa.Column('storage_path', sa.String(length=1000), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('youtube_video_id', sa.String(length=64), nullable=True),
    sa.Column('publish_status', sa.Enum('DRAFT', 'SCHEDULED', 'PUBLISHED', 'FAILED', name='publish_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_version_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'GENERATED', 'APPROVED', 'REJECTED', name='asset_status'), nullable=False),
    sa.Column('retry_reason', sa.String(), nullable=True),
    sa.Column('quality_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['thumbnail_id'], ['thumbnails.id'], ),
    sa.ForeignKeyConstraint(['workflow_run_id'], ['workflow_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analytics',
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('snapshot_at', sa.DateTime(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('subscribers_gained', sa.Integer(), nullable=False),
    sa.Column('click_through_rate', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('average_view_duration_seconds', sa.Float(), nullable=True),
    sa.Column('average_view_percentage', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('audience_drop_off_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analytics')
    op.drop_table('videos')
    op.drop_table('images')
    op.drop_table('generated_videos')
    op.drop_table('thumbnails')
    op.drop_table('storyboards')
    op.drop_table('system_logs')
    op.drop_table('scripts')
    op.drop_table('quality_score_details')
    op.drop_table('provider_usage_logs')
    op.drop_table('prompts')
    op.drop_table('generation_learning_events')
    op.drop_table('generation_attempts')
    op.drop_table('assets')
    op.drop_table('artifacts')
    op.drop_table('approval_checkpoints')
    op.drop_table('workflow_runs')
    op.drop_table('providers')
    op.drop_table('prompt_templates')
    op.drop_table('projects')
    op.drop_table('performance_learning_feedback')
    op.drop_table('feature_flags')
    # ### end Alembic commands ###

    # MANUALLY ADDED — see IMPLEMENTATION_GAP note: Alembic's
    # autogenerate does not emit DROP TYPE for Postgres ENUM types on
    # downgrade, even though it correctly creates them on upgrade.
    # Left as-is, downgrade() would silently leave 10 orphaned enum
    # types behind after dropping every table that used them —
    # verified by actually running downgrade against a real Postgres
    # instance during review. Dropped explicitly here, after all
    # tables referencing them are already gone.
    op.execute('DROP TYPE IF EXISTS approval_action')
    op.execute('DROP TYPE IF EXISTS approval_stage')
    op.execute('DROP TYPE IF EXISTS artifact_type')
    op.execute('DROP TYPE IF EXISTS asset_status')
    op.execute('DROP TYPE IF EXISTS prompt_artifact_type')
    op.execute('DROP TYPE IF EXISTS prompt_template_artifact_type')
    op.execute('DROP TYPE IF EXISTS provider_category')
    op.execute('DROP TYPE IF EXISTS publish_status')
    op.execute('DROP TYPE IF EXISTS workflow_mode')
    op.execute('DROP TYPE IF EXISTS workflow_status')
